"""add reminder_activate to users

Revision ID: 41fa67319331
Revises: 241489212595
Create Date: 2025-07-14 16:08:45.796623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fa67319331'
down_revision = '241489212595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_activate', sa.Boolean(), nullable=True))

    op.execute("UPDATE users SET reminder_activate = false")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('reminder_activate', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reminder_activate')

    # ### end Alembic commands ###
