"""Add reminder_timezone to users

Revision ID: fad3fc3b32bd
Revises: 41fa67319331
Create Date: 2025-07-14 17:20:00.977630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad3fc3b32bd'
down_revision = '41fa67319331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_timezone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reminder_timezone')

    # ### end Alembic commands ###
